services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx_container
    ports:
      - "443:443"
    networks:
      - inception
    # env_file: ./srcs/.env
networks:
  inception:
    driver: bridge
