services:
  mariadb:
    build: ./requirements/mariadb/
    # tag du container
    container_name: mariadb_container
    restart: always
    # Ouvre le port du container pour les autres container
    expose: 
      - "3306"
    env_file: .env
    volumes:
      - "mariadb:/var/lib/mysql"
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress_container
    restart: always
    expose:
      - "9000"
    depends_on:
      - mariadb
    volumes:
      - "wordpress:/var/www/wordpress"
    networks:
      - inception
    env_file: .env

  nginx:
    build: ./requirements/nginx/
    container_name: nginx_container
    restart: always
    # Ouvre le port du container et le connect aux ports du pc acutel
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - "wordpress:/var/www/wordpress"
    networks:
      - inception

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/rihoy/data/wordpress"
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/rihoy/data/mariadb"

networks:
  inception:
    driver: bridge
