FROM	debian:bullseye

RUN		apt update -y && apt-get install php-fpm curl php-mysql -y \
		&& mkdir -p /var/www/html/wordpress \
		&& mkdir -p /run/php

COPY	./tools/prompt.sh ./prompt.sh
RUN		chmod +x ./prompt.sh

EXPOSE 9000

COPY ./tools/config/wp-config.php /var/www/html/wordpress
RUN		chmod 644 /var/www/html/wordpress/wp-config.php

ENTRYPOINT [ "./prompt.sh" ]