FROM	debian:bullseye

	# Mise a jour et installation des paquets nécessaires
RUN apt update -y && apt-get install -y nginx openssl

	# Création des répertoires nécessaires
RUN mkdir -p /etc/nginx/certs

	# Génératino des du certificat auto-signé
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
	-keyout /etc/nginx/certs/nginx.key \
	-out /etc/nginx/certs/nginx.crt \
	-subj "/CN=rihoy.42.fr"

COPY ./config/nginx.conf ./etc/nginx/nginx.conf

	# Ouvre le port 443
EXPOSE	443

	# commande de démarrage de nginx
CMD ["nginx", "-g", "daemon off;"]