FROM	debian:bullseye

	# Mise a jour et installation des paquets nécessaires
RUN apt update -y && apt-get install -y nginx openssl \
	&& apt-get clean \
	&& rm -fr /var/lib/apt/lists/*

	# Création des répertoires nécessaires
RUN mkdir -p /etc/ssl/private /etc/ssl/certs

	# Génératino des du certificat auto-signé
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
	-keyout /etc/ssl/private/private.key \
	-out /etc/ssl/certs/certificate.crt \
	-subj "/CN=rihoy.42.fr"

COPY ./config/nginx.conf ./etc/nginx/nginx.conf

	# Ouvre le port 443
EXPOSE	443

	# commande de démarrage de nginx
CMD ["nginx", "-g", "daemon off;"]