FROM	debian:bullseye

RUN apt update -y && apt-get install nginx openssl -y
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
	-keyout /etc/ssl/private/private.key \
	-out /etc/ssl/certs/certificate.crt \
	-subj "/C=/ST=/L=/O=/OU=/CN=rihoy.42.fr"

COPY ./config/nginx.conf ./etc/nginx/nginx.conf

EXPOSE	443

CMD ["nginx", "-g", "daemon off;"]